-- =====================================================================
-- 0025_seed_challenge_history_feature.sql
--
-- §8's third payoff, and the one that is permanently forfeited if it is not
-- captured: "step-up outcome history is among the most predictive inputs a
-- system of this kind has, and it is generated by the system's own actions."
--
-- This file is the proof that the claim costs INSERTs. No migration, no reducer,
-- no engine change, no new relation — it is min_since_password_reset's exact
-- shape (0015, an events-sourced feature driven by transactions) with `count`
-- in place of `age_minutes_latest`.
--
-- Why it reads `events` and not `action_executions`, which is where the outcome
-- is actually stored — three reasons, each independently sufficient:
--
--   1. §8 says so: the new event types "carry the customer-facing side into the
--      behavioral log, WHERE THE NEXT GENERATION OF RULES CAN READ THEM".
--   2. action_executions.subject_id holds a TXN id for every R-114 decision, so
--      "failed step-ups on this CARD" is not expressible over that relation
--      without denormalising card_id onto it.
--   3. Reading it would need three code changes — ALLOWED_RELATIONS, TIME_COLUMN,
--      and a card-bearing column — which would make §14's "INSERTs only" claim
--      false for precisely the feature offered as evidence for it.
--
-- And why `challenge_failed` is its own event type rather than an attribute on
-- challenge_outcome: a filter_predicate names a bare COLUMN. predicate.py takes
-- identifiers only and rejects a dict value, so `attributes->>'outcome'` is
-- unreachable by design — that restriction is the injection boundary, and the
-- right answer is vocabulary (an INSERT into ref_event_type) rather than a hole
-- in the boundary.
--
-- No rule references this feature yet. That is deliberate: the catalog row and
-- the computed values are what §8 claims, and pricing a condition against four
-- observed challenges would be exactly the uncalibrated guess §10 objects to.
-- =====================================================================
BEGIN;

INSERT INTO ref_event_type (event_type, description) VALUES
 ('challenge_failed','A step-up challenge was failed or abandoned by the customer')
ON CONFLICT DO NOTHING;

INSERT INTO feature_catalog
 (feature_key, display_name, description, entity_type, value_type, window_spec,
  inline_capable, is_graph, source, default_reason_code)
VALUES
 ('card_challenge_fails_30d','Failed step-ups (30d)',
  'Step-up challenges this card failed or abandoned in the last 30 days',
  'card','numeric','30d',TRUE,FALSE,'derived','BEHAVIOR_DRIFT')
ON CONFLICT (feature_key) DO NOTHING;

UPDATE feature_catalog SET
  source_kind='aggregate', source_relation='events',
  subject_key='subject_id', scope_key='subject_id',
  aggregation='count', value_expr='event_id',
  -- The card is not the rule's subject; a transaction is. The resolution graph
  -- already carries transaction -> card (0016), which R-114's card features use.
  resolution_path='transaction.card_id',
  filter_predicate='{"op":"and","args":[
      {"op":"eq","col":"event_type","value":"challenge_failed"},
      {"op":"eq","col":"subject_type","value":"card"}]}'::jsonb,
  -- Driven by transactions, like every other feature whose meaning is "as of
  -- this movement". Driving it off events would only recompute on the rare days
  -- a challenge failed, and the value would be stale everywhere else — that is
  -- defect 4 of the Week-2 handoff, and it cost a debugging round there.
  baseline_spec='{"driver_relation":"transactions","driver_key":"card_id"}'::jsonb,
  -- Zero is a real answer: a card with no failed step-ups has none, and that is
  -- knowledge, not absence. Contrast every MITIGATOR, which must default to NULL
  -- (test_degraded.py enforces that across the catalog) — this is an
  -- aggravating-direction feature, so a default is safe here.
  default_when_absent='0'::jsonb,
  refresh='incremental', fanout_policy='one', spec_version=1,
  max_staleness='24 hours'
 WHERE feature_key='card_challenge_fails_30d';

COMMIT;
