"""Issuing what a decision authorised (§8).

Week 2's topology ended at `decisions`. Nothing issued a step-up, held an
account or notified an analyst, and the consequences were measurement ones
rather than plumbing ones:

  * "block rate" counted decisions to block rather than blocks;
  * a challenge the customer passed and one they abandoned were
    indistinguishable, so §7.3's argument that prevention needs a higher
    threshold — because a wrong block costs a customer — rested on a cost
    nobody could observe;
  * step-up outcome history, which is among the most predictive inputs a system
    of this kind has AND is generated by the system's own actions, was being
    thrown away permanently.

Two policy decisions are encoded here, both about not doing something twice.

**A preventive action is issued only when a case is RAISED.** Not on a fold: a
ring re-evaluated every fifteen minutes would otherwise send the customer 96
step-ups a day for one situation, which is the customer-facing version of
exactly the noise §9 exists to remove. Not on a restatement either — the score
got worse, but it is the same authorization and the challenge already went out.

**A notification IS re-issued on a restatement.** An open case getting worse is
news to an analyst, and a notification costs an analyst a glance rather than
costing a customer a declined card. That asymmetry is §7.3's, applied to
delivery instead of to thresholds.

`issued_at` is the decision's `occurred_at`, not now(). A replay of January must
produce January's executions, for the same reason the fold window is measured on
event time.
"""
from __future__ import annotations

import json
from typing import Any, Sequence

import psycopg

from ..db import fetch_all

# 'notify' is deliberately absent from ref_action (see 0013): it is a
# channel-level execution, not a rung on the severity ladder.
NOTIFY = "notify"


def _preventive_actions(conn: psycopg.Connection) -> frozenset[str]:
    """From ref_action, never a literal list — the ladder is ordered data and
    §7 reads is_preventive off the same rows."""
    return frozenset(r["action"] for r in fetch_all(
        conn, "SELECT action FROM ref_action WHERE is_preventive"))


def _routing(conn: psycopg.Connection) -> dict[tuple[str, str], str]:
    return {(r["action"], r["band"]): r["channel"] for r in fetch_all(
        conn, "SELECT action, band, channel FROM action_routing")}


def _trigger_rows(conn: psycopg.Connection, txn_ids: Sequence[str]) -> dict[str, dict]:
    """The card and customer behind each triggering transaction.

    Needed because the customer-facing side of an action is a fact about a CARD,
    not about the transaction that provoked it: "this card failed two step-ups
    last month" is the feature worth having, and it cannot be keyed on a txn_id
    that never recurs.
    """
    if not txn_ids:
        return {}
    rows = fetch_all(
        conn,
        "SELECT txn_id, card_id, customer_id, account_id FROM transactions "
        "WHERE txn_id = ANY(%s)",
        (list(txn_ids),),
    )
    return {r["txn_id"]: r for r in rows}


def write_executions(conn: psycopg.Connection,
                     routed: Sequence[tuple[Any, int, str]]) -> int:
    """One row per action actually issued. `routed` is (result, alert_id, kind)
    for the evaluations that reached a queue this batch."""
    actionable = [(r, aid, kind) for r, aid, kind in routed
                  if kind in ("raised", "restated")]
    if not actionable:
        return 0

    preventive = _preventive_actions(conn)
    routing = _routing(conn)
    triggers = _trigger_rows(
        conn, [r.request.trigger.id for r, _, _ in actionable
               if r.request.trigger and r.request.trigger.type == "transaction"])

    rows: list[tuple] = []
    events: list[tuple] = []
    for result, alert_id, kind in actionable:
        subject = result.request.subject
        issued_at = result.request.occurred_at
        action = result.outcome.action

        wanted = [NOTIFY]
        if action in preventive and kind == "raised":
            wanted.insert(0, action)

        for act in wanted:
            channel = routing.get((act, result.band))
            if channel is None:
                # Loud, never a default. A silent fallback channel would mean an
                # action was "issued" down a route nobody chose.
                raise LookupError(
                    f"no action_routing row for ({act!r}, band={result.band!r}); "
                    f"seed one in db/seeds/0024_seed_alert_policy.sql")
            rows.append((result.decision_id, act, channel, issued_at,
                         subject.type, subject.id, alert_id))

    with conn.cursor() as cur:
        placeholder = "(%s, %s, %s, %s, %s, %s, %s)"
        cur.execute(
            "INSERT INTO action_executions "
            "(decision_id, action, channel, issued_at, subject_type, subject_id, alert_id) "
            "VALUES " + ", ".join([placeholder] * len(rows))
            + " RETURNING execution_id, decision_id, action, channel",
            [v for row in rows for v in row],
        )
        issued = cur.fetchall()

    # The customer-facing half goes into the behavioural log, keyed on the card,
    # where the next generation of rules can read it as an ordinary feature
    # (§8, and db/seeds/0025). Nothing here is a side channel.
    by_decision = {r.decision_id: (r, t) for r, _, _ in actionable
                   for t in [triggers.get(
                       r.request.trigger.id if r.request.trigger else None, {})]}
    for row in issued:
        if row["action"] != "challenge":
            continue
        result, trigger = by_decision[row["decision_id"]]
        card_id = trigger.get("card_id")
        if card_id is None:
            continue
        events.append((
            result.request.occurred_at, "challenge_issued", "card", card_id,
            json.dumps({"execution_id": row["execution_id"],
                        "decision_id": row["decision_id"],
                        "channel": row["channel"]}),
        ))

    if events:
        with conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO events (occurred_at, event_type, subject_type, "
                "subject_id, attributes) VALUES (%s, %s, %s, %s, %s)",
                events,
            )
    return len(rows)
