"""Settling issued actions, and dispositioning the cases they opened (§8).

Nothing external answers a step-up here, so outcomes are SYNTHESISED — and every
row this module writes says so: `action_executions.synthetic = TRUE`, and since
0029, `case_outcomes.source = 'synthetic'`. Every rate computed from them is
published with that flag, because a synthetic challenge pass rate presented as a
measured one would be exactly the kind of claim this system exists not to make.
The dispositions needed the column once a human could write to the same table:
until Week 5 the settler identified itself only by writing the literal
`analyst_id = 'synthetic-analyst'`, which nothing could JOIN against.

The draw is deterministic — blake2b over (execution_id, subject) rather than
random.seed — so two runs settle identically, a test can assert that, and nothing
depends on global interpreter state. It is conditioned on
`transactions.synthetic_label`, which is the same fixture-only ground truth §11's
false-negative tile is computed against.

What this buys, none of which is available any other way (§8):

  * Prevention precision. A challenge that PASSED on a case later dispositioned
    `confirmed_legit` is a prevention false positive — a customer stopped for
    nothing. That case has been invisible until now, because blocked and
    challenged events never entered the alert queue and so never reached
    case_outcomes.
  * A feature. Step-up outcome history is among the strongest inputs a system
    like this has, and it is generated by the system's own actions. db/seeds/0025
    turns it into a catalog row.
  * Median triage time. case_outcomes.decided_at is written explicitly rather
    than defaulted to now(), so alerts.created_at -> decided_at is a duration
    rather than an artefact of when the script happened to run.

One divergence recorded rather than papered over: §8's table lists a `delivered`
outcome, but 0013's CHECK allows `completed`. Notifications settle as
`completed` + outcome_source `system`.
"""
from __future__ import annotations

import json
from datetime import timedelta
from hashlib import blake2b
from typing import Any

import psycopg

from ..db import fetch_all

# Conditioned on the label, and deliberately not degenerate in either direction.
# A fraudster does sometimes pass a step-up — SIM swap, social engineering, a
# compromised handset — and a genuine customer does sometimes abandon one. Both
# tails have to exist or "challenge pass rate" is just the label read back.
_FRAUD = ((0.70, "abandoned"), (0.95, "failed"), (1.00, "passed"))
_LEGIT = ((0.85, "passed"), (0.95, "abandoned"), (1.00, "failed"))

_SOURCE = {"passed": "customer", "failed": "customer", "abandoned": "timeout"}

_UNRESOLVED_SQL = """
SELECT ae.execution_id, ae.action, ae.issued_at, ae.decision_id, ae.alert_id,
       d.trigger_id, t.card_id, t.synthetic_label
  FROM action_executions ae
  JOIN decisions d ON d.decision_id = ae.decision_id
  LEFT JOIN transactions t ON t.txn_id = d.trigger_id
 WHERE ae.resolved_at IS NULL
 ORDER BY ae.execution_id
"""

# Open cases nobody has dispositioned yet. case_outcomes has no uniqueness
# constraint, so NOT EXISTS is the only thing standing between a second run and
# a second disposition — which would also fan out every join the §10 report makes
# through this table.
_UNDISPOSED_SQL = """
SELECT a.alert_id, a.first_event_at, a.subject_type, a.subject_id, a.score,
       d.decision_id, d.action_taken, d.trigger_id, t.synthetic_label
  FROM alerts a
  JOIN decisions d ON d.decision_id = a.decision_id
  LEFT JOIN transactions t ON t.txn_id = d.trigger_id
 WHERE a.status = 'open'
   AND NOT EXISTS (SELECT 1 FROM case_outcomes co WHERE co.alert_id = a.alert_id)
 ORDER BY a.alert_id
"""


def draw(*parts: Any) -> float:
    """A stable uniform [0,1) from the identity of the thing being decided.

    Not random.seed: a global seed makes the result depend on how many draws
    happened earlier, so inserting one execution would reshuffle every outcome
    after it and a re-run would silently disagree with the run it replaced.
    """
    digest = blake2b(":".join(str(p) for p in parts).encode(), digest_size=8).digest()
    return int.from_bytes(digest, "big") / 2 ** 64


def _outcome_for(label: str | None, u: float) -> str:
    table = _FRAUD if label == "fraud" else _LEGIT
    for edge, outcome in table:
        if u < edge:
            return outcome
    return table[-1][1]


def settle(conn: psycopg.Connection) -> dict[str, int]:
    """Resolve every unresolved execution, then disposition every open case."""
    rows = fetch_all(conn, _UNRESOLVED_SQL)

    updates: list[tuple] = []
    events: list[tuple] = []
    tally = {"challenges": 0, "passed": 0, "failed": 0, "abandoned": 0,
             "notifies": 0, "analyst": 0, "dispositions": 0}

    for row in rows:
        action, label = row["action"], row["synthetic_label"]

        if action == "notify":
            # Delivery is immediate and uninteresting; it is recorded so that
            # "was an analyst told" is answerable at all.
            updates.append((row["issued_at"], "completed", "system",
                            row["execution_id"]))
            tally["notifies"] += 1
            continue

        if action != "challenge":
            # hold / block: settled by the analyst working the case. `overridden`
            # means they released it, which on a legit-labelled subject is the
            # preventive action having been wrong.
            outcome = "overridden" if label != "fraud" else "completed"
            delay = timedelta(hours=1 + 6 * draw("triage", row["execution_id"]))
            updates.append((row["issued_at"] + delay, outcome, "analyst",
                            row["execution_id"]))
            tally["analyst"] += 1
            continue

        u = draw("challenge", row["execution_id"], row["decision_id"])
        outcome = _outcome_for(label, u)
        # A passed step-up comes back in seconds; an abandoned one only after the
        # window expires. The gap is what makes issued_at -> resolved_at a
        # latency measurement rather than a constant.
        minutes = 0.5 + 9.5 * draw("latency", row["execution_id"]) \
            if outcome != "abandoned" else 10.0
        resolved_at = row["issued_at"] + timedelta(minutes=minutes)
        updates.append((resolved_at, outcome, _SOURCE[outcome], row["execution_id"]))
        tally["challenges"] += 1
        tally[outcome] += 1

        if row["card_id"]:
            events.append((resolved_at, "challenge_outcome", "card", row["card_id"],
                           json.dumps({"execution_id": row["execution_id"],
                                       "outcome": outcome})))
            if outcome in ("failed", "abandoned"):
                # A separate event type, not an attribute, because a feature
                # spec can filter on event_type and cannot reach into
                # attributes: predicate.py takes bare column identifiers only,
                # by design. See db/seeds/0025.
                events.append((resolved_at, "challenge_failed", "card",
                               row["card_id"],
                               json.dumps({"execution_id": row["execution_id"],
                                           "outcome": outcome})))

    with conn.cursor() as cur:
        if updates:
            cur.executemany(
                "UPDATE action_executions SET resolved_at = %s, outcome = %s, "
                "outcome_source = %s, synthetic = TRUE WHERE execution_id = %s",
                updates,
            )
        if events:
            cur.executemany(
                "INSERT INTO events (occurred_at, event_type, subject_type, "
                "subject_id, attributes) VALUES (%s, %s, %s, %s, %s)",
                events,
            )

    tally["dispositions"] = _disposition(conn)
    return tally


def _disposition(conn: psycopg.Connection) -> int:
    """Write the analyst verdict every §11 rate is measured against.

    Truthful to the label rather than noisy on purpose: the point of measuring a
    false-positive rate here is to measure THE RULES, and an analyst error model
    on top would only blur the thing under test.

    `confirmed_legit` is reserved for the case §8 exists to expose — a customer
    who was challenged, passed, and turned out to be themselves. That is a
    prevention false positive, and it is distinct from a plain false positive
    where nothing was done to the customer at all.
    """
    rows = fetch_all(conn, _UNDISPOSED_SQL)
    if not rows:
        return 0

    passed = {r["decision_id"] for r in fetch_all(
        conn,
        "SELECT DISTINCT decision_id FROM action_executions "
        "WHERE action = 'challenge' AND outcome = 'passed'")}

    payload = []
    for row in rows:
        if row["synthetic_label"] == "fraud":
            disposition = "confirmed_fraud"
        elif row["decision_id"] in passed:
            disposition = "confirmed_legit"
        else:
            disposition = "false_positive"

        hours = 0.25 + 47.75 * draw("disposition", row["alert_id"])
        payload.append((
            row["alert_id"], disposition, "synthetic-analyst",
            row["first_event_at"] + timedelta(hours=hours),
            f"Synthetic disposition from transactions.synthetic_label "
            f"({row['synthetic_label']}). Fixture artifact, not an analyst judgement.",
        ))

    with conn.cursor() as cur:
        cur.executemany(
            "INSERT INTO case_outcomes (alert_id, disposition, analyst_id, "
            "decided_at, notes, source) VALUES (%s, %s, %s, %s, %s, 'synthetic')",
            payload,
        )
    return len(payload)
