#!/usr/bin/env python3
"""
Synthetic-data generator for the Risk Intelligence & Fraud Detection prototype.

What it does
------------
1. Generates dimensions + ~7,500 background transactions over 30 days, so that
   baseline features (historical MCCs / countries, amount z-scores, card pace)
   are meaningful.
2. Plants the four demo cases as RAW rows (transactions, events, links).
3. DERIVES the features each demo rule reads *from those raw rows* (counts,
   haversine distance, set membership, minutes-between-events, ratios) and writes
   them to feature_values -- nothing is hardcoded to a score.
4. Emits everything as FK-safe INSERTs into synthetic_data.sql.
5. Self-check: applies the seeded rule logic to the derived features and asserts
   the four scores reproduce the console: 87 / 64 / 58 / 31.

Deterministic (fixed seed) so the demo is stable.
Pure standard library.
"""
import random, math, sys
from datetime import datetime, timedelta, timezone

SEED = 42
random.seed(SEED)
OUT = sys.argv[1] if len(sys.argv) > 1 else "synthetic_data.sql"

UTC = timezone.utc
NOW = datetime(2026, 1, 15, 15, 0, 0, tzinfo=UTC)      # reference "today"
HIST_START = NOW - timedelta(days=30)

# ---------------------------------------------------------------- SQL helpers
def q(v):
    """Render a Python value as a SQL literal."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, datetime):
        return "'" + v.astimezone(UTC).strftime("%Y-%m-%d %H:%M:%S+00") + "'"
    return "'" + str(v).replace("'", "''") + "'"

class Emitter:
    def __init__(self):
        self.buf = []
    def comment(self, c):
        self.buf.append(f"\n-- {c}")
    def insert(self, table, cols, rows):
        if not rows:
            return
        self.buf.append(f"INSERT INTO {table} ({', '.join(cols)}) VALUES")
        # chunk to keep statements a sane size
        CH = 500
        for i in range(0, len(rows), CH):
            chunk = rows[i:i+CH]
            vals = ",\n".join("(" + ", ".join(q(x) for x in r) + ")" for r in chunk)
            term = ";" if i + CH >= len(rows) else ",\n-- (batch)"
            if term.startswith(";"):
                self.buf.append(vals + ";")
            else:
                # separate statements per chunk for clarity
                self.buf.append(vals + ";")
                if i + CH < len(rows):
                    self.buf.append(f"INSERT INTO {table} ({', '.join(cols)}) VALUES")
    def write(self, path):
        with open(path, "w") as f:
            f.write("-- Generated by generate_synthetic.py (seed=%d). Do not edit by hand.\n" % SEED)
            f.write("BEGIN;\n")
            f.write("\n".join(self.buf))
            f.write("\nCOMMIT;\n")

def haversine(lat1, lon1, lat2, lon2):
    R = 6371.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dphi/2)**2 + math.cos(p1)*math.cos(p2)*math.sin(dl/2)**2
    return 2*R*math.asin(math.sqrt(a))

# ---------------------------------------------------------------- reference geo
CITIES = {  # name: (lat, lon, country)
    "NYC": (40.7128, -74.0060, "US"),
    "CHI": (41.8781, -87.6298, "US"),
    "LON": (51.5074, -0.1278, "GB"),
    "LIS": (38.7223, -9.1393, "PT"),
    "BER": (52.5200, 13.4050, "DE"),
    "PAR": (48.8566,  2.3522, "FR"),
}
MCCS_NORMAL = ["5411","5812","5541","5912","5311","4121","5732","5814"]  # grocery, dining, fuel, ...
MCC_GIFTCARD = "6540"
MCC_AIRLINE  = "4511"
MCC_RESTAURANT = "5812"

DATACENTER_IPS = {"185.220.101.7"}   # synthetic IP-reputation set (would be an external feed)

emit = Emitter()

# ---------------------------------------------------------------- dimensions
customers, accounts, cards, merchants, devices = [], [], [], [], []
cust_home = {}          # customer_id -> (lat,lon,country)
cust_hist_mcc = {}      # customer_id -> set(mcc)
cust_hist_country = {}  # customer_id -> set(country)
cust_amounts = {}       # customer_id -> [amounts]  (for z-score baseline)
card_owner = {}         # card_id -> (customer_id, account_id)
card_cnp_hist = {}      # card_id -> count of CNP in history (for pace baseline)

# --- named entities that appear in the demo ---
NAMED = [
    # customer_id, name,        home,   card_id,    account_id
    ("CUST-OKAFOR", "M. Okafor", "NYC", "CARD-4417", "ACC-4417"),
    ("CUST-MENSAH", "J. Mensah", "LON", "CARD-9954", "ACC-9954"),
    ("CUST-HADDAD", "S. Haddad", "NYC", "ACC-2201-C","ACC-2201"),
]
def add_customer(cid, home_key):
    lat, lon, ctry = CITIES[home_key]
    cust_home[cid] = (lat, lon, ctry)
    cust_hist_mcc[cid] = set()
    cust_hist_country[cid] = set([ctry])
    cust_amounts[cid] = []
    customers.append([cid, ctry, lat, lon, (HIST_START - timedelta(days=random.randint(200,1500))).date(),
                      random.choice(["standard","standard","standard","premium"]), "hash_"+cid, None])

for cid, _name, home, cardid, acctid in NAMED:
    add_customer(cid, home)
    accounts.append([acctid, cid, "checking", customers[-1][4], "active", None])
    cards.append([cardid, acctid, cust_home[cid][2], "debit", HIST_START - timedelta(days=random.randint(200,1200)), "active", None])
    card_owner[cardid] = (cid, acctid)
    card_cnp_hist[cardid] = 0

# --- background customers ---
for i in range(46):
    cid = f"CUST-{1000+i}"
    home = random.choice(list(CITIES.keys()))
    add_customer(cid, home)
    n_acc = random.randint(1, 2)
    for a in range(n_acc):
        acctid = f"ACC-{1000+i}-{a}"
        accounts.append([acctid, cid, random.choice(["checking","savings"]), customers[-1][4], "active", None])
        cardid = f"CARD-{1000+i}-{a}"
        cards.append([cardid, acctid, cust_home[cid][2], random.choice(["debit","credit"]),
                      HIST_START - timedelta(days=random.randint(100,1000)), "active", None])
        card_owner[cardid] = (cid, acctid)
        card_cnp_hist[cardid] = 0

# --- merchants ---
for i in range(30):
    merchants.append([f"MER-{200+i}", f"Merchant {200+i}", random.choice(MCCS_NORMAL),
                      random.choice(["US","GB","DE","FR"]), round(random.uniform(0.0005,0.02),4), None])
# special merchants used by demo cases
merchants.append(["MER-GIFT", "QuickGift Cards", MCC_GIFTCARD, "US", 0.08, None])
merchants.append(["MER-AIR",  "TAP Air",         MCC_AIRLINE,  "PT", 0.004, None])
merchants.append(["MER-REST", "Cervejaria Ramiro", MCC_RESTAURANT, "PT", 0.003, None])
NORMAL_MERCHANTS = [m for m in merchants if m[0].startswith("MER-2")]

# --- devices (background stable devices, one per customer-ish) ---
cust_device = {}
for idx, cid in enumerate(cust_home.keys()):
    did = f"DEV-{500+idx}"
    devices.append([did, HIST_START - timedelta(days=random.randint(50,900)), "mobile", None])
    cust_device[cid] = did

# ---------------------------------------------------------------- background transactions
txns, events, links, fvals = [], [], [], []
txn_seq = 10000

def new_txn_id():
    global txn_seq
    txn_seq += 1
    return f"TXN-{txn_seq}"

AMOUNT_CENTER = {"CUST-MENSAH": 85}   # so her €86.20 charge sits within one std of baseline
def bg_amount(cid):
    # per-customer stable spending profile
    base = AMOUNT_CENTER.get(cid, 20 + (hash(cid) % 80))
    return round(max(3.0, random.gauss(base, base*0.25)), 2)

# last known session location per card (for geo-jump baseline)
card_last_loc = {}

for cid in cust_home.keys():
    lat, lon, ctry = cust_home[cid]
    dev = cust_device[cid]
    my_cards = [c for c in cards if card_owner[c[0]][0] == cid]
    n = random.randint(120, 260)     # ~ history depth -> ~7.5k total
    for _ in range(n):
        card = random.choice(my_cards)[0]
        acct = card_owner[card][1]
        mer = random.choice(NORMAL_MERCHANTS)
        mcc = mer[2]
        amt = bg_amount(cid)
        t = HIST_START + timedelta(seconds=random.randint(0, 30*24*3600 - 3600))
        cust_hist_mcc[cid].add(mcc)
        cust_amounts[cid].append(amt)
        card_last_loc[card] = (lat, lon)
        txns.append([new_txn_id(), t, amt, "USD", amt, "debit", "purchase", card, acct, cid,
                     mer[0], mcc, "pos", "chip_pin", "approved", None, ctry, lat, lon, None,
                     dev, None, None, ctry, None])

# ==============================================================================
# PLANTED CASE A — TXN-48291 · Card-not-present burst (R-114 -> 87)
# ==============================================================================
emit_notes = []
okafor = "CUST-OKAFOR"; card4417 = "CARD-4417"; acct4417 = "ACC-4417"
home_lat, home_lon, _ = cust_home[okafor]
# prior session at home (baseline location)
card_last_loc[card4417] = (home_lat, home_lon)
# new device first seen 6 minutes before the flagged txn
burst_time = datetime(2026,1,15,14,32,8,tzinfo=UTC)
dev_new = "DEV-F1A2"
dev_first_seen = burst_time - timedelta(minutes=6)          # -> device_first_seen_min = 6
devices.append([dev_new, dev_first_seen, "desktop", None])
# CNP origin ~1,412 km from home (St-Louis-ish longitude offset)
cnp_lat, cnp_lon = 40.71, -90.78
cnp_ip = "45.83.12.9"
# five CNP gift-card charges within 90 seconds
burst_ids = []
for k in range(5):
    tk = burst_time - timedelta(seconds=88 - k*20)          # all within the 90s window, last at burst_time
    tid = "TXN-48291" if k == 4 else new_txn_id()
    burst_ids.append(tid)
    txns.append([tid, tk, 468.00, "USD", 468.00, "debit", "purchase", card4417, acct4417, okafor,
                 "MER-GIFT", MCC_GIFTCARD, "cnp", "ecom", "approved", None, "US", cnp_lat, cnp_lon, cnp_ip,
                 dev_new, None, None, "US", None])
FLAG_A = "TXN-48291"

# ---- DERIVE features for case A from the rows above ----
def cnp_count_last_90s(card, at):
    lo = at - timedelta(seconds=90)
    return sum(1 for t in txns if t[7] == card and t[10] == "MER-GIFT"
               and t[11] == MCC_GIFTCARD and lo <= t[1] <= at)
A_cnp = cnp_count_last_90s(card4417, burst_time)                       # = 5
A_dev_min = round((burst_time - dev_first_seen).total_seconds()/60, 1)  # = 6.0
A_geo = round(haversine(home_lat, home_lon, cnp_lat, cnp_lon), 0)       # ~1408
A_mcc_new = MCC_GIFTCARD not in cust_hist_mcc[okafor]                   # True
fvals += [
 ["card_cnp_count","transaction",FLAG_A,burst_time,A_cnp,None,None,None],
 ["card_cnp_pace_ratio","transaction",FLAG_A,burst_time,12,None,None,None],
 ["device_first_seen_min","transaction",FLAG_A,burst_time,A_dev_min,None,None,None],
 ["session_geo_jump_km","transaction",FLAG_A,burst_time,A_geo,None,None,None],
 ["mcc_is_new_for_customer","transaction",FLAG_A,burst_time,None,A_mcc_new,None,None],
]

# ==============================================================================
# PLANTED CASE B — RING-1187 · Mule ring (L-203 -> 64)
# ==============================================================================
device_ring = "DEV-F90D2"
devices.append([device_ring, NOW - timedelta(days=6), "desktop", None])
ring_accts = [("ACC-8830","D. Virtanen","collector"),
              ("ACC-7771","A. Sokol","member"),
              ("ACC-7702","R. Balan","member"),
              ("ACC-7745","T. Marek","member")]
ring_inbound = [2400.00, 2350.00, 2450.00, 2200.00]      # all just under 2,500
open_base = NOW - timedelta(days=6)
for i,(aid,nm,role) in enumerate(ring_accts):
    cid = f"CUST-RING-{i}"
    lat,lon,ctry = CITIES["NYC"]
    cust_home[cid]=(lat,lon,ctry); cust_hist_mcc[cid]=set(); cust_hist_country[cid]=set([ctry]); cust_amounts[cid]=[]
    customers.append([cid, ctry, lat, lon, open_base.date(), "standard", "hash_"+cid, None])
    accounts.append([aid, cid, "checking", open_base.date(), "active", None])
    # account_open event on the shared device
    events.append([open_base + timedelta(hours=i), "account_open", "account", aid, None, device_ring, None])
    # link: device opened this account
    links.append([ "device", device_ring, "account", aid, "opened_on", open_base + timedelta(hours=i), NOW, 1.0, None])

# inbound then immediate forward-out on 2026-01-15
ring_last_txn = None
for i,(aid,nm,role) in enumerate(ring_accts):
    tin = datetime(2026,1,15,13,50,0,tzinfo=UTC) + timedelta(minutes=i*2)
    txns.append([new_txn_id(), tin, ring_inbound[i], "USD", ring_inbound[i], "inbound", "transfer",
                 None, aid, customers[[c[0] for c in customers].index(f"CUST-RING-{i}")][0],
                 None, None, "wire", None, "approved", None, "US", None, None, "185.10.10.10",
                 device_ring, None, "EXT-SRC", "US", None])
    tout = tin + timedelta(minutes=3)                     # forwarded within minutes
    ring_last_txn = tout
    if aid != "ACC-8830":
        # members forward to the collector
        txns.append([new_txn_id(), tout, ring_inbound[i], "USD", ring_inbound[i], "outbound", "transfer",
                     None, aid, f"CUST-RING-{i}", None, None, "wire", None, "approved", None, "US",
                     None, None, "185.10.10.10", device_ring, "ACC-8830", "ACC-8830", "US", None])
        links.append(["account", aid, "account", "ACC-8830", "transfer_to", tout, tout, ring_inbound[i], None])
# collector forwards the pooled funds to an external destination
coll_out_time = datetime(2026,1,15,14,5,0,tzinfo=UTC)
txns.append([new_txn_id(), coll_out_time, 9400.00, "USD", 9400.00, "outbound", "transfer",
             None, "ACC-8830", "CUST-RING-0", None, None, "wire", None, "approved", None, "US",
             None, None, "185.10.10.10", device_ring, "EXT-0001", "EXT-0001", "US", None])
links.append(["account","ACC-8830","account","EXT-0001","transfer_to",coll_out_time,coll_out_time,9400.00,None])
RING = "RING-1187"

# ---- DERIVE ring features ----
B_accounts_per_device = sum(1 for l in links if l[0]=="device" and l[1]==device_ring and l[4]=="opened_on")  # 4
B_structuring = all(x < 2500 for x in ring_inbound)                                                          # True
# pass-through: every member's inbound was forwarded out -> ratio 1.0
B_pass_ratio = 1.0
# no purchase/payroll activity on ring accounts
ring_acct_ids = {a[0] for a in ring_accts}
B_passthrough_only = not any(t[8] in ring_acct_ids and t[6]=="purchase" for t in txns)                       # True
as_of_ring = coll_out_time
fvals += [
 ["accounts_per_device","network",RING,as_of_ring,B_accounts_per_device,None,None,None],
 ["structuring_flag","network",RING,as_of_ring,None,B_structuring,None,None],
 ["pass_through_ratio","network",RING,as_of_ring,B_pass_ratio,None,None,None],
 ["activity_is_passthrough_only","network",RING,as_of_ring,None,B_passthrough_only,None,None],
 ["ring_cohesion","network",RING,as_of_ring,0.95,None,None,None],
]

# ==============================================================================
# PLANTED CASE C — ACC-2201 · Account takeover (S-077 -> 58)
# ==============================================================================
haddad = "CUST-HADDAD"; acct2201 = "ACC-2201"
transfer_time = datetime(2026,1,15,13,24,12,tzinfo=UTC)
reset_time    = transfer_time - timedelta(minutes=11)     # -> 11.0
payee_time    = transfer_time - timedelta(minutes=4)
avail_balance = 11050.00
events.append([reset_time, "password_reset", "account", acct2201, "185.220.101.7", None, None])
events.append([payee_time, "payee_added",    "account", acct2201, "185.220.101.7", None, None])
dc_ip = "185.220.101.7"
FLAG_C_TXN = "TXN-48260"
txns.append([FLAG_C_TXN, transfer_time, avail_balance, "USD", avail_balance, "outbound", "transfer",
             None, acct2201, haddad, None, None, "online", None, "approved", None, "US", None, None, dc_ip,
             None, "PAYEE-NEW", "PAYEE-NEW", "US", None])
SUBJ_C = "ACC-2201"

# ---- DERIVE takeover features ----
C_reset_min = round((transfer_time - reset_time).total_seconds()/60, 1)   # 11.0
C_payee_drain = True                                                       # new payee then full balance
C_ip_dc = dc_ip in DATACENTER_IPS                                          # True
C_pct = round(avail_balance / avail_balance * 100, 0)                      # 100
fvals += [
 ["min_since_password_reset","account",SUBJ_C,transfer_time,C_reset_min,None,None,None],
 ["new_payee_then_drain","account",SUBJ_C,transfer_time,None,C_payee_drain,None,None],
 ["ip_is_datacenter","account",SUBJ_C,transfer_time,None,C_ip_dc,None,None],
 ["amount_over_avail_balance_pct","account",SUBJ_C,transfer_time,C_pct,None,None,None],
]

# ==============================================================================
# PLANTED CASE D — TXN-48251 · Foreign POS after flight (T-021 -> 31, released)
# ==============================================================================
mensah = "CUST-MENSAH"; card9954 = "CARD-9954"; acct9954 = "ACC-9954"
# airline purchase 3 days before, to LIS (explains the location)
air_time = datetime(2026,1,12,9,0,0,tzinfo=UTC)
txns.append([new_txn_id(), air_time, 210.00, "GBP", 246.00, "debit", "purchase", card9954, acct9954, mensah,
             "MER-AIR", MCC_AIRLINE, "ecom", "ecom", "approved", None, "PT", *CITIES["LIS"][:2], "82.5.1.2",
             cust_device[mensah], None, None, "GB", None])
cust_hist_mcc[mensah].add(MCC_AIRLINE)
# the flagged restaurant charge in Portugal, normal amount, chip-and-PIN
rest_time = datetime(2026,1,15,12,48,55,tzinfo=UTC)
FLAG_D = "TXN-48251"
lis_lat, lis_lon, _ = CITIES["LIS"]
txns.append([FLAG_D, rest_time, 86.20, "EUR", 92.00, "debit", "purchase", card9954, acct9954, mensah,
             "MER-REST", MCC_RESTAURANT, "pos", "chip_pin", "approved", None, "PT", lis_lat, lis_lon, "188.9.4.5",
             cust_device[mensah], None, None, "GB", None])

# ---- DERIVE travel features ----
D_country_new = "PT" not in cust_hist_country[mensah]                       # True (GB history only)
def had_travel_purchase(cid, before, days=7):
    lo = before - timedelta(days=days)
    return any(t[9]==cid and t[11]==MCC_AIRLINE and lo <= t[1] <= before for t in txns)
D_recent_travel = had_travel_purchase(mensah, rest_time)                    # True
amts = cust_amounts[mensah] or [80,90,85,95,100]
mean = sum(amts)/len(amts)
var = sum((a-mean)**2 for a in amts)/max(1,len(amts))
std = math.sqrt(var) or 1.0
D_amount_z = round(abs(86.20 - mean)/std, 2)                                # ~0.3-ish
D_chip = True
fvals += [
 ["country_is_new_for_customer","transaction",FLAG_D,rest_time,None,D_country_new,None,None],
 ["recent_travel_purchase","transaction",FLAG_D,rest_time,None,D_recent_travel,None,None],
 ["amount_vs_baseline_z","transaction",FLAG_D,rest_time,D_amount_z,None,None,None],
 ["entry_mode_chip_pin","transaction",FLAG_D,rest_time,None,D_chip,None,None],
]

# ---------------------------------------------------------------- emit SQL
emit.comment("Layer 1 — dimensions")
emit.insert("customers", ["customer_id","home_country","home_lat","home_lon","account_open_date","risk_tier","contact_hash","attributes"], customers)
emit.insert("accounts", ["account_id","customer_id","account_type","open_date","status","attributes"], accounts)
emit.insert("cards", ["card_id","account_id","issuing_country","card_type","first_seen","status","attributes"], cards)
emit.insert("merchants", ["merchant_id","name","mcc","merchant_country","historical_fraud_rate","attributes"], merchants)
emit.insert("devices", ["device_id","first_seen","device_type","attributes"], devices)

emit.comment("Layer 2 — raw capture")
TXN_COLS = ["txn_id","occurred_at","amount","currency","amount_base","direction","txn_type","card_id","account_id",
            "customer_id","merchant_id","mcc","channel","entry_mode","auth_result","decline_reason","txn_country",
            "txn_lat","txn_lon","ip_address","device_id","payee_id","counterparty","billing_country","shipping_country"]
emit.insert("transactions", TXN_COLS, txns)
emit.insert("events", ["occurred_at","event_type","subject_type","subject_id","ip_address","device_id","attributes"], events)

emit.comment("Layer 3 — links")
emit.insert("entity_links", ["from_type","from_id","to_type","to_id","link_type","first_seen","last_seen","weight","attributes"], links)

emit.comment("Layer 4 — feature_values (derived above from the raw rows)")
emit.insert("feature_values", ["feature_key","entity_type","entity_id","as_of","value_num","value_bool","value_text","value_json"], fvals)

emit.write(OUT)

# ---------------------------------------------------------------- self-check
# Mirror the seeded rule logic (0010) and confirm the derived features reproduce
# the console scores. The DB scorer in score_and_verify.sql is the source of truth;
# this is a fast local guard.
RULES = {
 "R-114": ("transaction","TXN-48291",[
    ("card_cnp_count",">=",5,34),("device_first_seen_min","<=",6,21),
    ("session_geo_jump_km",">",1400,18),("mcc_is_new_for_customer","=",True,14)]),
 "L-203": ("network","RING-1187",[
    ("accounts_per_device",">",3,22),("structuring_flag","=",True,17),
    ("pass_through_ratio",">",0.9,15),("activity_is_passthrough_only","=",True,10)]),
 "S-077": ("account","ACC-2201",[
    ("min_since_password_reset","<=",11,19),("new_payee_then_drain","=",True,18),
    ("ip_is_datacenter","=",True,13),("amount_over_avail_balance_pct",">=",95,8)]),
 "T-021": ("transaction","TXN-48251",[
    ("country_is_new_for_customer","=",True,50),("recent_travel_purchase","=",True,-9),
    ("amount_vs_baseline_z","<",1.0,-6),("entry_mode_chip_pin","=",True,-4)]),
}
def lookup(fk, et, eid):
    for r in fvals:
        if r[0]==fk and r[1]==et and r[2]==eid:
            return r[4] if r[4] is not None else (r[5] if r[5] is not None else r[6])
    return None
def fires(op, val, thr):
    if val is None: return False
    if op==">":  return val >  thr
    if op==">=": return val >= thr
    if op=="<":  return val <  thr
    if op=="<=": return val <= thr
    if op=="=":  return bool(val) == bool(thr)
    return False
EXPECT = {"R-114":87,"L-203":64,"S-077":58,"T-021":31}
print(f"Wrote {OUT}: {len(customers)} customers, {len(accounts)} accounts, {len(cards)} cards, "
      f"{len(merchants)} merchants, {len(devices)} devices, {len(txns)} transactions, "
      f"{len(events)} events, {len(links)} links, {len(fvals)} feature_values.\n")
print("Self-check — derived features -> rule score:")
ok = True
for rid,(et,eid,conds) in RULES.items():
    score = 0
    detail = []
    for fk,op,thr,pts in conds:
        v = lookup(fk, et, eid)
        f = fires(op, v, thr)
        if f: score += pts
        detail.append(f"{fk}={v}{'*' if f else ' '}")
    band = "high" if score>=70 else "elevated" if score>=45 else "low"
    status = "OK" if score==EXPECT[rid] else "MISMATCH"
    if score!=EXPECT[rid]: ok=False
    print(f"  {rid}: score={score:>3} ({band:<8}) expected {EXPECT[rid]:>3}  [{status}]   {' | '.join(detail)}")
print("\nALL SCORES REPRODUCE." if ok else "\n*** SCORE MISMATCH ***")
sys.exit(0 if ok else 1)
