-- Generated by scripts/export_expectations.py from expected_scores.json.
-- Do not edit by hand. Included by db/acceptance/verify_scores.sql so that no
-- file under db/ has to name a fixture.
WITH expected(rule_id, subject_type, subject_id, exp_score, exp_action) AS (
  VALUES ('R-114', 'transaction', 'TXN-48291', 87, 'challenge'),
         ('L-203', 'network', 'RING-1187', 64, 'hold'),
         ('S-077', 'account', 'ACC-2201', 58, 'hold'),
         ('T-021', 'transaction', 'TXN-48251', 0, 'allow'),
         ('R-114+T-021', 'transaction', 'TXN-48300', 68, 'monitor')
)
SELECT e.subject_id,
       e.rule_id      AS demo_rule,
       d.score        AS computed,
       e.exp_score    AS expected,
       d.band,
       d.action_taken AS action,
       e.exp_action   AS expected_action,
       CASE WHEN d.score = e.exp_score AND d.action_taken = e.exp_action
            THEN 'OK' ELSE 'MISMATCH' END AS check
  FROM expected e
  LEFT JOIN LATERAL (
       SELECT score, band, action_taken FROM decisions
        WHERE subject_type = e.subject_type AND subject_id = e.subject_id
        ORDER BY decision_id DESC LIMIT 1
  ) d ON TRUE
 ORDER BY e.exp_score DESC;
