#!/usr/bin/env python3
"""Render fixtures/expected_scores.json into a psql-includable query.

db/acceptance/verify_scores.sql must contain NO literal subject ids — §3.3's
acceptance criterion is that nothing in db/ names a fixture. The expectations
still have to come from somewhere, so they come from the JSON, through here,
into fixtures/ where naming fixtures is the whole point.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from glassbox import config  # noqa: E402

OUT = config.FIXTURES_DIR / "expected_scores.sql"


def sql_literal(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


def render(data: dict) -> str:
    rows = ",\n         ".join(
        "(" + ", ".join(sql_literal(c[k]) for k in
                        ("rule_id", "subject_type", "subject_id", "score", "action")) + ")"
        for c in data["cases"]
    )
    return f"""-- Generated by scripts/export_expectations.py from expected_scores.json.
-- Do not edit by hand. Included by db/acceptance/verify_scores.sql so that no
-- file under db/ has to name a fixture.
WITH expected(rule_id, subject_type, subject_id, exp_score, exp_action) AS (
  VALUES {rows}
)
SELECT e.subject_id,
       e.rule_id      AS demo_rule,
       d.score        AS computed,
       e.exp_score    AS expected,
       d.band,
       d.action_taken AS action,
       e.exp_action   AS expected_action,
       CASE WHEN d.score = e.exp_score AND d.action_taken = e.exp_action
            THEN 'OK' ELSE 'MISMATCH' END AS check
  FROM expected e
  LEFT JOIN LATERAL (
       SELECT score, band, action_taken FROM decisions
        WHERE subject_type = e.subject_type AND subject_id = e.subject_id
        ORDER BY decision_id DESC LIMIT 1
  ) d ON TRUE
 ORDER BY e.exp_score DESC;
"""


def main() -> int:
    data = json.loads((config.FIXTURES_DIR / "expected_scores.json").read_text(encoding="utf-8"))
    OUT.write_text(render(data), encoding="utf-8")
    print(f"wrote {OUT}  ({len(data['cases'])} cases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
