#!/usr/bin/env python3
"""Generate the published contract schemas from the Pydantic models.

The output is COMMITTED. test_contract.py regenerates each one in memory and
asserts byte-equality, so this script is the only way a published schema changes
and changing it is always a reviewable diff. alert.v1 additionally has its
sha256 pinned in the test, because byte-equality alone passes if you change a
model AND re-run this script — the digest is what makes the freeze real rather
than conventional.

Never edit a committed schema by hand, and never edit one to match a model
change. A breaking change to alert.v1 becomes alert.v2.schema.json alongside it;
v1 keeps being served for whoever already bound to it.

New READ SURFACES are siblings, not new versions of the alert contract: queue.v1
and executions.v1 publish what §8 and §9 produced without touching a byte of
alert.v1. That is the whole reason models.py was left alone — Subject, Signal,
Action and Evidence live inside alert.v1's $defs closure.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from glassbox import config                       # noqa: E402
from glassbox.contract.executions import ExecutionRecord  # noqa: E402
from glassbox.contract.explanation import CaseReport, CopilotResponse  # noqa: E402
from glassbox.contract.kpis import KpiSet, KpiTile  # noqa: E402
from glassbox.contract.models import AlertDetail, AlertSummary  # noqa: E402
from glassbox.contract.queue import QueueEntry    # noqa: E402

# name -> (title, models). Order is irrelevant: the document is dumped with
# sort_keys=True, which is also why appending anything to alert.v1's $defs would
# change the file's bytes.
CONTRACTS: dict[str, tuple[str, tuple[type, ...]]] = {
    "alert.v1": ("GlassBox alert read contract, version 1",
                 (AlertDetail, AlertSummary)),
    "queue.v1": ("GlassBox review queue contract, version 1",
                 (QueueEntry,)),
    "executions.v1": ("GlassBox action execution contract, version 1",
                      (ExecutionRecord,)),
    "kpis.v1": ("GlassBox analytics contract, version 1",
                (KpiSet, KpiTile)),
    "explanation.v1": ("GlassBox explanation contract, version 1",
                       (CopilotResponse, CaseReport)),
}


def path_for(name: str) -> Path:
    return config.CONTRACT_DIR / f"{name}.schema.json"


# Kept as a module-level name: test_contract.py resolves the frozen alert
# contract through it, and it is the one path with a pinned digest.
SCHEMA_PATH = path_for("alert.v1")


def render(name: str = "alert.v1") -> str:
    title, models = CONTRACTS[name]
    successor = name.rsplit(".v", 1)[0] + ".v2.schema.json"
    document = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"https://glassbox.local/contract/{name}.schema.json",
        "title": title,
        "description": (
            "Frozen. Generated by scripts/export_contract_schema.py from "
            "src/glassbox/contract/models.py. Do not edit by hand; a breaking "
            f"change becomes {successor} and v1 keeps being served."
        ),
        "$defs": {
            model.__name__: model.model_json_schema(ref_template="#/$defs/{model}")
            for model in models
        },
    }
    return json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def main() -> int:
    config.CONTRACT_DIR.mkdir(parents=True, exist_ok=True)
    changed = False
    for name in CONTRACTS:
        path = path_for(name)
        text = render(name)
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        path.write_text(text, encoding="utf-8")
        print(("unchanged " if existing == text else "WROTE     ") + str(path))
        changed = changed or (existing is not None and existing != text)
    if changed:
        print("  a published contract changed — this must be a deliberate, reviewed diff")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
