#!/usr/bin/env python3
"""Generate contract/alert.v1.schema.json from the Pydantic models.

The output is COMMITTED. test_contract.py regenerates it in memory and asserts
byte-equality, so this script is the only way the published schema changes and
changing it is always a reviewable diff.

Never edit alert.v1.schema.json by hand, and never edit it to match a model
change. A breaking change becomes alert.v2.schema.json alongside it; v1 keeps
being served for whoever already bound to it.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from glassbox import config                       # noqa: E402
from glassbox.contract.models import AlertDetail, AlertSummary  # noqa: E402

SCHEMA_PATH = config.CONTRACT_DIR / "alert.v1.schema.json"


def render() -> str:
    document = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://glassbox.local/contract/alert.v1.schema.json",
        "title": "GlassBox alert read contract, version 1",
        "description": (
            "Frozen. Generated by scripts/export_contract_schema.py from "
            "src/glassbox/contract/models.py. Do not edit by hand; a breaking "
            "change becomes alert.v2.schema.json and v1 keeps being served."
        ),
        "$defs": {
            "AlertDetail": AlertDetail.model_json_schema(ref_template="#/$defs/{model}"),
            "AlertSummary": AlertSummary.model_json_schema(ref_template="#/$defs/{model}"),
        },
    }
    return json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def main() -> int:
    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    text = render()
    existing = SCHEMA_PATH.read_text(encoding="utf-8") if SCHEMA_PATH.exists() else None
    SCHEMA_PATH.write_text(text, encoding="utf-8")
    print(("unchanged " if existing == text else "WROTE     ") + str(SCHEMA_PATH))
    if existing is not None and existing != text:
        print("  the published contract changed — this must be a deliberate, reviewed diff")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
