#!/usr/bin/env python3
"""
Synthetic-data generator for the GlassBox risk prototype.

What it does
------------
1. Generates dimensions + ~7,700 background transactions over 30 days, so that
   baseline features (historical MCCs / countries, amount z-scores, card pace)
   are meaningful.
2. Plants five demo cases as RAW rows (transactions, events, links) only.
3. Adds a scored population: declines, refunds, a labelled fraud cohort, and a
   card-testing burst — so §10/§11 have something to measure and §14 has
   something to detect.
4. Emits everything as FK-safe INSERTs into fixtures/synthetic_data.sql.
5. Self-check: STRUCTURAL assertions about the rows it wrote.

What it deliberately does NOT do
--------------------------------
It does not write feature_values, and it does not compute scores.

The previous version derived 19 of 21 features in Python — counts, haversine,
z-scores, minutes-between-events — and wrote them straight to feature_values.
That is a second implementation of the feature layer, and §3.1's own argument
applies to it: if serving and training each implement a feature separately they
will diverge, and the divergence is invisible. The feature runner reading the
catalog is now the only implementation. Its agreement with the values this file
used to derive is pinned in tests/test_feature_runner.py.

The one exception is HAND_SEEDED_FEATURES below: new_payee_then_drain is a
sequence feature and the sequence runner is Week 3. One hand-seeded value out
of 21 is honest; nineteen was the situation this rewrite exists to end.

Deterministic (fixed seed) so the demo is stable. Pure standard library.
"""
import math
import random
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

SEED = 42
random.seed(SEED)

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT = sys.argv[1] if len(sys.argv) > 1 else str(REPO_ROOT / "fixtures" / "synthetic_data.sql")

UTC = timezone.utc
NOW = datetime(2026, 1, 15, 15, 0, 0, tzinfo=UTC)      # reference "today"
HIST_START = NOW - timedelta(days=30)

# ---------------------------------------------------------------- SQL helpers
def q(v):
    """Render a Python value as a SQL literal."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, datetime):
        return "'" + v.astimezone(UTC).strftime("%Y-%m-%d %H:%M:%S.%f+00") + "'"
    return "'" + str(v).replace("'", "''") + "'"


class Emitter:
    def __init__(self):
        self.buf = []

    def comment(self, c):
        self.buf.append(f"\n-- {c}")

    def insert(self, table, cols, rows):
        if not rows:
            return
        CH = 500
        for i in range(0, len(rows), CH):
            chunk = rows[i:i + CH]
            self.buf.append(f"INSERT INTO {table} ({', '.join(cols)}) VALUES")
            self.buf.append(",\n".join("(" + ", ".join(q(x) for x in r) + ")" for r in chunk) + ";")

    def write(self, path):
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write("-- Generated by scripts/generate_synthetic.py (seed=%d). Do not edit by hand.\n" % SEED)
            f.write("BEGIN;\n")
            f.write("\n".join(self.buf))
            f.write("\nCOMMIT;\n")


def haversine(lat1, lon1, lat2, lon2):
    R = 6371.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * R * math.asin(math.sqrt(a))


# ---------------------------------------------------------------- reference geo
CITIES = {  # name: (lat, lon, country)
    "NYC": (40.7128, -74.0060, "US"),
    "CHI": (41.8781, -87.6298, "US"),
    "LON": (51.5074, -0.1278, "GB"),
    "LIS": (38.7223, -9.1393, "PT"),
    "BER": (52.5200, 13.4050, "DE"),
    "PAR": (48.8566, 2.3522, "FR"),
}
MCCS_NORMAL = ["5411", "5812", "5541", "5912", "5311", "4121", "5732", "5814"]
MCC_GIFTCARD = "6540"
MCC_AIRLINE = "4511"
MCC_RESTAURANT = "5812"
MCC_BAR = "5813"          # the veto fixture's "new category"
MCC_SOFTWARE = "5734"     # the card-testing merchant

# Synthetic IP-reputation set. Must match the `set` in 0015's baseline_spec for
# ip_is_datacenter — the seed is authoritative, this is the fixture side of it.
DATACENTER_IPS = ["185.220.101.7", "185.220.102.11", "185.220.103.22"]

DECLINE_REASONS = (
    ["insufficient_funds"] * 40 + ["do_not_honor"] * 25 + ["invalid_cvv"] * 15
    + ["expired_card"] * 12 + ["suspected_fraud"] * 8
)

emit = Emitter()

TXN_COLS = ["txn_id", "occurred_at", "amount", "currency", "amount_base", "direction", "txn_type",
            "card_id", "account_id", "customer_id", "merchant_id", "mcc", "channel", "entry_mode",
            "auth_result", "decline_reason", "txn_country", "txn_lat", "txn_lon", "ip_address",
            "device_id", "payee_id", "counterparty", "billing_country", "shipping_country",
            "synthetic_label"]
_TXN_DEFAULTS = {c: None for c in TXN_COLS}
_TXN_DEFAULTS.update(currency="USD", direction="debit", txn_type="purchase",
                     auth_result="approved", synthetic_label="legit")


def mk_txn(**kw):
    """Build a transactions row. Positional column lists are how the old
    generator introduced silent column-shift bugs; this makes that impossible."""
    unknown = set(kw) - set(TXN_COLS)
    if unknown:
        raise KeyError(f"unknown transaction column(s): {sorted(unknown)}")
    row = dict(_TXN_DEFAULTS, **kw)
    if row["amount_base"] is None:
        row["amount_base"] = row["amount"]
    return [row[c] for c in TXN_COLS]


# ---------------------------------------------------------------- dimensions
customers, accounts, cards, merchants, devices = [], [], [], [], []
cust_home = {}
cust_device = {}
card_owner = {}

NAMED = [
    ("CUST-OKAFOR", "M. Okafor", "NYC", "CARD-4417", "ACC-4417"),
    ("CUST-MENSAH", "J. Mensah", "LON", "CARD-9954", "ACC-9954"),
    ("CUST-HADDAD", "S. Haddad", "NYC", "ACC-2201-C", "ACC-2201"),
    ("CUST-VETO",   "R. Alves",  "LON", "CARD-VETO", "ACC-VETO"),
    ("CUST-REFUND", "K. Ilves",  "NYC", "CARD-REF",  "ACC-REF"),
]


def add_customer(cid, home_key):
    lat, lon, ctry = CITIES[home_key]
    cust_home[cid] = (lat, lon, ctry)
    customers.append([cid, ctry, lat, lon,
                      (HIST_START - timedelta(days=random.randint(200, 1500))).date(),
                      random.choice(["standard", "standard", "standard", "premium"]),
                      "hash_" + cid, None])


for cid, _name, home, cardid, acctid in NAMED:
    add_customer(cid, home)
    accounts.append([acctid, cid, "checking", customers[-1][4], "active", None])
    cards.append([cardid, acctid, cust_home[cid][2], "debit",
                  HIST_START - timedelta(days=random.randint(200, 1200)), "active", None])
    card_owner[cardid] = (cid, acctid)

for i in range(46):
    cid = f"CUST-{1000+i}"
    add_customer(cid, random.choice(list(CITIES.keys())))
    for a in range(random.randint(1, 2)):
        acctid = f"ACC-{1000+i}-{a}"
        accounts.append([acctid, cid, random.choice(["checking", "savings"]),
                         customers[-1][4], "active", None])
        cardid = f"CARD-{1000+i}-{a}"
        cards.append([cardid, acctid, cust_home[cid][2], random.choice(["debit", "credit"]),
                      HIST_START - timedelta(days=random.randint(100, 1000)), "active", None])
        card_owner[cardid] = (cid, acctid)

for i in range(30):
    merchants.append([f"MER-{200+i}", f"Merchant {200+i}", random.choice(MCCS_NORMAL),
                      random.choice(["US", "GB", "DE", "FR"]), round(random.uniform(0.0005, 0.02), 4), None])
merchants.append(["MER-GIFT", "QuickGift Cards", MCC_GIFTCARD, "US", 0.08, None])
merchants.append(["MER-AIR",  "TAP Air", MCC_AIRLINE, "PT", 0.004, None])
merchants.append(["MER-REST", "Cervejaria Ramiro", MCC_RESTAURANT, "PT", 0.003, None])
merchants.append(["MER-BAR",  "A Ginjinha", MCC_BAR, "PT", 0.002, None])
merchants.append(["MER-TEST", "Nimbus Softworks", MCC_SOFTWARE, "US", 0.21, None])
NORMAL_MERCHANTS = [m for m in merchants if m[0].startswith("MER-2")]

for idx, cid in enumerate(list(cust_home.keys())):
    did = f"DEV-{500+idx}"
    devices.append([did, HIST_START - timedelta(days=random.randint(50, 900)), "mobile", None])
    cust_device[cid] = did

# ---------------------------------------------------------------- background transactions
txns, events, links = [], [], []
txn_seq = 10000
cust_amounts = {cid: [] for cid in cust_home}


def new_txn_id():
    global txn_seq
    txn_seq += 1
    return f"TXN-{txn_seq}"


AMOUNT_CENTER = {"CUST-MENSAH": 85, "CUST-VETO": 60}


def bg_amount(cid):
    base = AMOUNT_CENTER.get(cid, 20 + (hash(cid) % 80))
    return round(max(3.0, random.gauss(base, base * 0.25)), 2)


for cid in list(cust_home.keys()):
    lat, lon, ctry = cust_home[cid]
    dev = cust_device[cid]
    my_cards = [c for c in cards if card_owner[c[0]][0] == cid]
    for _ in range(random.randint(120, 260)):
        card = random.choice(my_cards)[0]
        acct = card_owner[card][1]
        mer = random.choice(NORMAL_MERCHANTS)
        amt = bg_amount(cid)
        t = HIST_START + timedelta(seconds=random.randint(0, 30 * 24 * 3600 - 3600))
        cust_amounts[cid].append(amt)
        # ~3% of purchases are declined, with an auth_declined event alongside.
        declined = random.random() < 0.03
        txns.append(mk_txn(
            txn_id=new_txn_id(), occurred_at=t, amount=amt, merchant_id=mer[0], mcc=mer[2],
            card_id=card, account_id=acct, customer_id=cid, channel="pos", entry_mode="chip_pin",
            auth_result="declined" if declined else "approved",
            decline_reason=random.choice(DECLINE_REASONS) if declined else None,
            txn_country=ctry, txn_lat=lat, txn_lon=lon, device_id=dev, billing_country=ctry))
        if declined:
            events.append([t, "auth_declined", "card", card, None, dev, None])

# ~1.8% of approved purchases are refunded 1-20 days later.
_approved_bg = [t for t in txns if t[14] == "approved"]
for src in random.sample(_approved_bg, int(len(_approved_bg) * 0.018)):
    rt = src[1] + timedelta(days=random.randint(1, 20), seconds=random.randint(0, 86399))
    if rt >= NOW:
        continue
    txns.append(mk_txn(
        txn_id=new_txn_id(), occurred_at=rt, amount=src[2], direction="credit", txn_type="refund",
        card_id=src[7], account_id=src[8], customer_id=src[9], merchant_id=src[10], mcc=src[11],
        channel="pos", txn_country=src[16], txn_lat=src[17], txn_lon=src[18], device_id=src[20]))
    events.append([rt, "refund_issued", "card", src[7], None, None, None])

# ==============================================================================
# PLANTED CASE A - TXN-48291 · Card-not-present burst (R-114 -> 87)
# ==============================================================================
okafor, card4417, acct4417 = "CUST-OKAFOR", "CARD-4417", "ACC-4417"
home_lat, home_lon, _ = cust_home[okafor]
burst_time = datetime(2026, 1, 15, 14, 32, 8, tzinfo=UTC)
dev_new = "DEV-F1A2"
dev_first_seen = burst_time - timedelta(minutes=6)          # -> device_first_seen_min = 6.0
devices.append([dev_new, dev_first_seen, "desktop", None])
cnp_lat, cnp_lon = 40.71, -90.78                            # ~1,412 km from NYC
cnp_ip = "45.83.12.9"
FLAG_A = "TXN-48291"
for k in range(5):
    # The LAST charge lands exactly on burst_time, so device_first_seen_min
    # reads 6.0 rather than 5.87 and the seeded signal text stays literally true.
    tk = burst_time - timedelta(seconds=80 - k * 20)        # all inside the 90s window
    txns.append(mk_txn(
        txn_id=FLAG_A if k == 4 else new_txn_id(), occurred_at=tk, amount=468.00,
        card_id=card4417, account_id=acct4417, customer_id=okafor,
        merchant_id="MER-GIFT", mcc=MCC_GIFTCARD, channel="cnp", entry_mode="ecom",
        txn_country="US", txn_lat=cnp_lat, txn_lon=cnp_lon, ip_address=cnp_ip,
        device_id=dev_new, billing_country="US", synthetic_label="fraud"))

# ==============================================================================
# PLANTED CASE B - RING-1187 · Mule ring (L-203 -> 64)
# ==============================================================================
device_ring = "DEV-F90D2"
devices.append([device_ring, NOW - timedelta(days=6), "desktop", None])
ring_accts = [("ACC-8830", "collector"), ("ACC-7771", "member"),
              ("ACC-7702", "member"), ("ACC-7745", "member")]
ring_inbound = [2400.00, 2350.00, 2450.00, 2200.00]         # all just under 2,500
open_base = NOW - timedelta(days=6)
for i, (aid, role) in enumerate(ring_accts):
    cid = f"CUST-RING-{i}"
    lat, lon, ctry = CITIES["NYC"]
    cust_home[cid] = (lat, lon, ctry)
    cust_amounts[cid] = []
    customers.append([cid, ctry, lat, lon, open_base.date(), "standard", "hash_" + cid, None])
    accounts.append([aid, cid, "checking", open_base.date(), "active", None])
    events.append([open_base + timedelta(hours=i), "account_open", "account", aid, None, device_ring, None])
    links.append(["device", device_ring, "account", aid, "opened_on",
                  open_base + timedelta(hours=i), NOW, 1.0, None])

# The last inbound is what triggers L-203's async evaluation. At that instant the
# members have not yet forwarded — which is exactly why evaluation_lag exists.
ring_last_inbound = None
for i, (aid, role) in enumerate(ring_accts):
    tin = datetime(2026, 1, 15, 13, 50, 0, tzinfo=UTC) + timedelta(minutes=i * 2)
    ring_last_inbound = tin
    txns.append(mk_txn(
        txn_id=new_txn_id(), occurred_at=tin, amount=ring_inbound[i], direction="inbound",
        txn_type="transfer", account_id=aid, customer_id=f"CUST-RING-{i}", channel="wire",
        txn_country="US", ip_address="185.10.10.10", device_id=device_ring,
        counterparty="EXT-SRC", billing_country="US", synthetic_label="fraud"))
    tout = tin + timedelta(minutes=3)
    if aid != "ACC-8830":
        txns.append(mk_txn(
            txn_id=new_txn_id(), occurred_at=tout, amount=ring_inbound[i], direction="outbound",
            txn_type="transfer", account_id=aid, customer_id=f"CUST-RING-{i}", channel="wire",
            txn_country="US", ip_address="185.10.10.10", device_id=device_ring,
            payee_id="ACC-8830", counterparty="ACC-8830", billing_country="US",
            synthetic_label="fraud"))
        links.append(["account", aid, "account", "ACC-8830", "transfer_to", tout, tout, ring_inbound[i], None])
coll_out_time = datetime(2026, 1, 15, 14, 5, 0, tzinfo=UTC)
txns.append(mk_txn(
    txn_id=new_txn_id(), occurred_at=coll_out_time, amount=9400.00, direction="outbound",
    txn_type="transfer", account_id="ACC-8830", customer_id="CUST-RING-0", channel="wire",
    txn_country="US", ip_address="185.10.10.10", device_id=device_ring,
    payee_id="EXT-0001", counterparty="EXT-0001", billing_country="US", synthetic_label="fraud"))
links.append(["account", "ACC-8830", "account", "EXT-0001", "transfer_to",
              coll_out_time, coll_out_time, 9400.00, None])

# ==============================================================================
# PLANTED CASE C - ACC-2201 · Account takeover (S-077 -> 58)
# ==============================================================================
haddad, acct2201 = "CUST-HADDAD", "ACC-2201"
transfer_time = datetime(2026, 1, 15, 13, 24, 12, tzinfo=UTC)
reset_time = transfer_time - timedelta(minutes=11)          # -> min_since_password_reset = 11.0
payee_time = transfer_time - timedelta(minutes=4)
AVAIL_BALANCE = 11050.00
dc_ip = DATACENTER_IPS[0]
events.append([reset_time, "password_reset", "account", acct2201, dc_ip, None, None])
events.append([payee_time, "payee_added", "account", acct2201, dc_ip, None, None])

# amount_over_avail_balance_pct DERIVES the balance as credits - debits (there is
# no balance column and no ledger). So the fixture has to make the balance real:
# plant payroll credits sized against the debits actually generated above, so the
# balance standing immediately before the transfer is exactly AVAIL_BALANCE.
_debits_before = sum(
    t[2] for t in txns
    if t[8] == acct2201 and t[1] < transfer_time and t[5] in ("debit", "outbound")
    and t[14] == "approved")
_credits_before = sum(
    t[2] for t in txns
    if t[8] == acct2201 and t[1] < transfer_time and t[5] in ("credit", "inbound"))
_payroll_times = [transfer_time - timedelta(days=d, hours=9) for d in (28, 14, 2)]
_payroll_needed = AVAIL_BALANCE + _debits_before - _credits_before
_payroll = [round(_payroll_needed * 0.35, 2), round(_payroll_needed * 0.35, 2)]
_payroll.append(round(_payroll_needed - sum(_payroll), 2))
assert all(p > 0 for p in _payroll), f"payroll split went non-positive: {_payroll}"
for pt, amt in zip(_payroll_times, _payroll):
    txns.append(mk_txn(
        txn_id=new_txn_id(), occurred_at=pt, amount=amt, direction="credit", txn_type="payment",
        account_id=acct2201, customer_id=haddad, channel="wire", txn_country="US",
        counterparty="EMPLOYER-PAYROLL", billing_country="US"))

FLAG_C_TXN = "TXN-48260"
txns.append(mk_txn(
    txn_id=FLAG_C_TXN, occurred_at=transfer_time, amount=AVAIL_BALANCE, direction="outbound",
    txn_type="transfer", account_id=acct2201, customer_id=haddad, channel="online",
    txn_country="US", ip_address=dc_ip, payee_id="PAYEE-NEW", counterparty="PAYEE-NEW",
    billing_country="US", synthetic_label="fraud"))

# ==============================================================================
# PLANTED CASE D - TXN-48251 · Foreign POS after flight (T-021 -> 31, released)
# ==============================================================================
mensah, card9954, acct9954 = "CUST-MENSAH", "CARD-9954", "ACC-9954"
air_time = datetime(2026, 1, 12, 9, 0, 0, tzinfo=UTC)
# The ticket is bought ONLINE FROM HOME: txn_country is where the purchase
# happened (GB), not where the airline is (PT). The previous fixture recorded it
# as PT, which makes Portugal a country the customer had already transacted in —
# so a real country_is_new_for_customer would read FALSE and silently cost
# T-021 the +50 its signed-off score of 31 is built from.
txns.append(mk_txn(
    txn_id=new_txn_id(), occurred_at=air_time, amount=210.00, currency="GBP", amount_base=246.00,
    card_id=card9954, account_id=acct9954, customer_id=mensah, merchant_id="MER-AIR",
    mcc=MCC_AIRLINE, channel="ecom", entry_mode="ecom", txn_country="GB",
    txn_lat=CITIES["LON"][0], txn_lon=CITIES["LON"][1], ip_address="82.5.1.2",
    device_id=cust_device[mensah], billing_country="GB"))
cust_amounts[mensah].append(246.00)

rest_time = datetime(2026, 1, 15, 12, 48, 55, tzinfo=UTC)
FLAG_D = "TXN-48251"
lis_lat, lis_lon, _ = CITIES["LIS"]
txns.append(mk_txn(
    txn_id=FLAG_D, occurred_at=rest_time, amount=86.20, currency="EUR", amount_base=92.00,
    card_id=card9954, account_id=acct9954, customer_id=mensah, merchant_id="MER-REST",
    mcc=MCC_RESTAURANT, channel="pos", entry_mode="chip_pin", txn_country="PT",
    txn_lat=lis_lat, txn_lon=lis_lon, ip_address="188.9.4.5",
    device_id=cust_device[mensah], billing_country="GB"))

# ==============================================================================
# PLANTED CASE E - TXN-48300 · The veto fixture (NEW — see judgment call 1)
# ==============================================================================
# §7's acceptance criterion reads "a veto rule scoring 31 demonstrably caps a
# score of 87 at monitor". The 31 is T-021 on TXN-48251 and the 87 is R-114 on
# TXN-48291 — DIFFERENT SUBJECTS. A veto caps severity within one (subject,
# lane, evaluation) and must not reach across to another transaction, so as
# written the criterion cannot pass without an engine that is wrong.
#
# This is the fifth fixture that makes it passable, and it is a real scenario
# rather than a contrivance: a customer is abroad with a newly-registered phone
# while their card number is simultaneously being tested online from another
# country. R-114's four conditions genuinely hold (they are card- and
# device-level). T-021's three exonerating conditions genuinely hold (they are
# about THIS charge: chip-and-PIN present, amount normal, travel on file).
# The right answer is not to challenge this charge — it is to watch it.
veto_cust, veto_card, veto_acct = "CUST-VETO", "CARD-VETO", "ACC-VETO"
lon_lat, lon_lon, _ = cust_home[veto_cust]

# Portugal is NOT new for this customer — a trip last month. That is what keeps
# T-021's +50 aggravator from firing, so the fixture lands at 68 rather than 118.
for d, amt in ((26, 41.50), (25, 88.00), (24, 22.75)):
    txns.append(mk_txn(
        txn_id=new_txn_id(), occurred_at=NOW - timedelta(days=d, hours=4), amount=amt,
        card_id=veto_card, account_id=veto_acct, customer_id=veto_cust,
        merchant_id="MER-REST", mcc=MCC_RESTAURANT, channel="pos", entry_mode="chip_pin",
        txn_country="PT", txn_lat=lis_lat, txn_lon=lis_lon,
        device_id=cust_device[veto_cust], billing_country="GB"))
    cust_amounts[veto_cust].append(amt)

txns.append(mk_txn(   # the ticket, bought from home three days ago
    txn_id=new_txn_id(), occurred_at=datetime(2026, 1, 12, 11, 30, 0, tzinfo=UTC),
    amount=189.00, currency="GBP", amount_base=221.00,
    card_id=veto_card, account_id=veto_acct, customer_id=veto_cust, merchant_id="MER-AIR",
    mcc=MCC_AIRLINE, channel="ecom", entry_mode="ecom", txn_country="GB",
    txn_lat=lon_lat, txn_lon=lon_lon, device_id=cust_device[veto_cust], billing_country="GB"))

veto_time = datetime(2026, 1, 15, 14, 45, 0, tzinfo=UTC)
dev_veto_phone = "DEV-V001"          # the traveller's newly set-up handset
dev_veto_fraud = "DEV-V002"          # the card tester's machine, deliberately NOT new
devices.append([dev_veto_phone, veto_time - timedelta(minutes=6), "mobile", None])
devices.append([dev_veto_fraud, HIST_START - timedelta(days=200), "desktop", None])
for k in range(5):                   # the CNP burst on the same card
    txns.append(mk_txn(
        txn_id=new_txn_id(), occurred_at=veto_time - timedelta(seconds=88 - k * 20),
        amount=312.00, card_id=veto_card, account_id=veto_acct, customer_id=veto_cust,
        merchant_id="MER-GIFT", mcc=MCC_GIFTCARD, channel="cnp", entry_mode="ecom",
        txn_country="US", txn_lat=cnp_lat, txn_lon=cnp_lon, ip_address=cnp_ip,
        device_id=dev_veto_fraud, billing_country="GB", synthetic_label="fraud"))
FLAG_E = "TXN-48300"
txns.append(mk_txn(   # the genuine charge: card present, normal amount, new category
    txn_id=FLAG_E, occurred_at=veto_time, amount=31.40, currency="EUR", amount_base=33.50,
    card_id=veto_card, account_id=veto_acct, customer_id=veto_cust, merchant_id="MER-BAR",
    mcc=MCC_BAR, channel="pos", entry_mode="chip_pin", txn_country="PT",
    txn_lat=lis_lat, txn_lon=lis_lon, ip_address="188.9.4.9",
    device_id=dev_veto_phone, billing_country="GB"))

# ==============================================================================
# POPULATION - card-testing burst at MER-TEST (§14's extension target)
# ==============================================================================
CARDTEST_START = datetime(2026, 1, 14, 3, 12, 0, tzinfo=UTC)
_pool = [c for c in cards if c[0].startswith("CARD-10")][:14]
assert len(_pool) == 14, f"expected 14 background cards for the card-testing pool, got {len(_pool)}"
for n in range(22):
    c = _pool[n % 14]
    cid_, aid_ = card_owner[c[0]]
    t = CARDTEST_START + timedelta(seconds=int(n * (8 * 60) / 22))
    txns.append(mk_txn(
        txn_id=new_txn_id(), occurred_at=t, amount=round(random.uniform(1.0, 5.0), 2),
        card_id=c[0], account_id=aid_, customer_id=cid_, merchant_id="MER-TEST",
        mcc=MCC_SOFTWARE, channel="cnp", entry_mode="keyed", auth_result="declined",
        decline_reason=random.choice(["invalid_cvv", "do_not_honor"]),
        txn_country="US", ip_address=DATACENTER_IPS[1 + (n % 2)],
        billing_country="US", synthetic_label="fraud"))
    events.append([t, "auth_declined", "card", c[0], DATACENTER_IPS[1 + (n % 2)], None, None])
# the tell: two of them go through at an identical trivial amount
for n, c in enumerate(_pool[:2]):
    cid_, aid_ = card_owner[c[0]]
    txns.append(mk_txn(
        txn_id=new_txn_id(), occurred_at=CARDTEST_START + timedelta(minutes=6, seconds=n * 7),
        amount=2.10, card_id=c[0], account_id=aid_, customer_id=cid_, merchant_id="MER-TEST",
        mcc=MCC_SOFTWARE, channel="cnp", entry_mode="keyed", txn_country="US",
        ip_address=DATACENTER_IPS[1], billing_country="US", synthetic_label="fraud"))

# ==============================================================================
# POPULATION - refund abuse (subject shape: customer — unlike all five demos)
# ==============================================================================
refund_cust, refund_card, refund_acct = "CUST-REFUND", "CARD-REF", "ACC-REF"
_ref_purchases = []
for n in range(11):
    pt = NOW - timedelta(days=14 - n, hours=6)
    amt = round(random.uniform(60, 240), 2)
    tid = new_txn_id()
    mer = NORMAL_MERCHANTS[n % len(NORMAL_MERCHANTS)]
    txns.append(mk_txn(
        txn_id=tid, occurred_at=pt, amount=amt, card_id=refund_card, account_id=refund_acct,
        customer_id=refund_cust, merchant_id=mer[0], mcc=mer[2], channel="ecom",
        entry_mode="ecom", txn_country="US", txn_lat=cust_home[refund_cust][0],
        txn_lon=cust_home[refund_cust][1], device_id=cust_device[refund_cust],
        billing_country="US"))
    _ref_purchases.append((tid, pt, amt, mer))
    cust_amounts[refund_cust].append(amt)
_ref_total = sum(p[2] for p in _ref_purchases)
_ref_emitted = 0.0
for n, (tid, pt, amt, mer) in enumerate(_ref_purchases):
    # two refunds deliberately exceed the original — the shape that makes this abuse
    ramt = round(amt * (1.15 if n < 2 else 0.80), 2)
    _ref_emitted += ramt
    txns.append(mk_txn(
        txn_id=new_txn_id(), occurred_at=pt + timedelta(days=1, hours=3), amount=ramt,
        direction="credit", txn_type="refund", card_id=refund_card, account_id=refund_acct,
        customer_id=refund_cust, merchant_id=mer[0], mcc=mer[2], channel="ecom",
        txn_country="US", device_id=cust_device[refund_cust], synthetic_label="fraud"))
    events.append([pt + timedelta(days=1, hours=3), "refund_issued", "card", refund_card, None, None, None])

# ==============================================================================
# POPULATION - labelled fraud cohort (§11's false-negative tile)
# ==============================================================================
# 22 small CNP clusters, deliberately sized so most fall BELOW R-114's line. A
# cohort the rules catch entirely makes the FN tile read 0% and proves nothing.
#   clusters  0-5   : 5-7 charges, new device, big geo jump, new MCC  -> detectable
#   clusters  6-10  : 5-7 charges but a known device and no geo jump  -> missed
#   clusters 11-21  : 3-4 charges, under the count threshold          -> missed
_cohort_cards = [c for c in cards if c[0].startswith("CARD-10")][14:36]
assert len(_cohort_cards) >= 22, f"cohort needs 22 spare cards, found {len(_cohort_cards)}"
cohort_expect_detected = 0
for n in range(22):
    c = _cohort_cards[n][0]
    cid_, aid_ = card_owner[c]
    hl, hn, hc = cust_home[cid_]
    base_t = HIST_START + timedelta(days=random.randint(2, 27), seconds=random.randint(0, 80000))
    if n < 6:
        count, dev_id, mcc_, lat_, lon_ = random.randint(5, 7), f"DEV-C{n:02d}", MCC_GIFTCARD, 40.71, -90.78
        devices.append([dev_id, base_t - timedelta(minutes=5), "desktop", None])
        cohort_expect_detected += 1
    elif n < 11:
        count, dev_id, mcc_, lat_, lon_ = random.randint(5, 7), cust_device[cid_], random.choice(MCCS_NORMAL), hl, hn
    else:
        count, dev_id, mcc_, lat_, lon_ = random.randint(3, 4), cust_device[cid_], random.choice(MCCS_NORMAL), hl, hn
    for k in range(count):
        txns.append(mk_txn(
            txn_id=new_txn_id(), occurred_at=base_t + timedelta(seconds=k * 14),
            amount=round(random.uniform(40, 260), 2), card_id=c, account_id=aid_,
            customer_id=cid_,
            merchant_id="MER-GIFT" if n < 6 else NORMAL_MERCHANTS[n % len(NORMAL_MERCHANTS)][0],
            mcc=mcc_, channel="cnp", entry_mode="ecom", txn_country=hc, txn_lat=lat_, txn_lon=lon_,
            device_id=dev_id, billing_country=hc, synthetic_label="fraud"))

# ==============================================================================
# HAND_SEEDED_FEATURES  —  TODO(week3): delete this block
# ==============================================================================
# new_payee_then_drain is source_kind='sequence' and the sequence runner is
# Week 3 work (§17 accepts S-077 stays hand-specified for one more week). This
# is the ONLY feature value this file writes. S-077's other three features are
# genuinely computed by the runner, so the case still exercises resolution,
# point-in-time reads and the `trigger` root for real.
HAND_SEEDED_FEATURES = [
    ["new_payee_then_drain", "account", acct2201, transfer_time, None, True, None, None,
     transfer_time, 1],
]

# ---------------------------------------------------------------- emit SQL
txns.sort(key=lambda r: (r[1], r[0]))
events.sort(key=lambda r: (r[0], r[1]))

emit.comment("Layer 1 - dimensions")
emit.insert("customers", ["customer_id", "home_country", "home_lat", "home_lon",
                          "account_open_date", "risk_tier", "contact_hash", "attributes"], customers)
emit.insert("accounts", ["account_id", "customer_id", "account_type", "open_date", "status", "attributes"], accounts)
emit.insert("cards", ["card_id", "account_id", "issuing_country", "card_type", "first_seen", "status", "attributes"], cards)
emit.insert("merchants", ["merchant_id", "name", "mcc", "merchant_country", "historical_fraud_rate", "attributes"], merchants)
emit.insert("devices", ["device_id", "first_seen", "device_type", "attributes"], devices)

emit.comment("Layer 2 - raw capture")
emit.insert("transactions", TXN_COLS, txns)
emit.insert("events", ["occurred_at", "event_type", "subject_type", "subject_id",
                       "ip_address", "device_id", "attributes"], events)

emit.comment("Layer 3 - links")
emit.insert("entity_links", ["from_type", "from_id", "to_type", "to_id", "link_type",
                             "first_seen", "last_seen", "weight", "attributes"], links)

emit.comment("Layer 4 - the ONE hand-seeded feature value (see HAND_SEEDED_FEATURES)")
emit.insert("feature_values", ["feature_key", "entity_type", "entity_id", "as_of", "value_num",
                               "value_bool", "value_text", "value_json", "computed_at",
                               "spec_version"], HAND_SEEDED_FEATURES)

emit.write(OUT)

# ---------------------------------------------------------------- self-check
# STRUCTURAL assertions only. This file no longer computes features, so it can
# no longer honestly assert scores — that is what db/acceptance/verify_scores.sql
# and fixtures/expected_scores.json are for, both reading the real engine output.
failures = []


def check(label, ok, detail=""):
    print(f"  [{'OK ' if ok else 'FAIL'}] {label}{('  - ' + detail) if detail else ''}")
    if not ok:
        failures.append(label)


_IDX = {c: i for i, c in enumerate(TXN_COLS)}


def txns_where(**kw):
    return [t for t in txns if all(t[_IDX[k]] == v for k, v in kw.items())]


print(f"\nWrote {OUT}")
print(f"  {len(customers)} customers, {len(accounts)} accounts, {len(cards)} cards, "
      f"{len(merchants)} merchants, {len(devices)} devices")
print(f"  {len(txns)} transactions, {len(events)} events, {len(links)} links, "
      f"{len(HAND_SEEDED_FEATURES)} hand-seeded feature value\n")
print("Structural self-check:")

_burst = [t for t in txns_where(card_id=card4417, channel="cnp")
          if burst_time - timedelta(seconds=90) < t[1] <= burst_time]
check("A: 5 CNP charges on CARD-4417 within 90s", len(_burst) == 5, f"{len(_burst)}")
check("A: DEV-F1A2 first seen 6.0 min before the burst",
      (burst_time - dev_first_seen).total_seconds() / 60 == 6.0)
_geo = haversine(home_lat, home_lon, cnp_lat, cnp_lon)
check("A: geo jump exceeds R-114's 1400 km line", _geo > 1400, f"{_geo:.0f} km")
check("A: MCC 6540 unused by CUST-OKAFOR before the burst day",
      not [t for t in txns_where(customer_id=okafor, mcc=MCC_GIFTCARD)
           if t[1] <= burst_time - timedelta(days=1)])

check("B: 4 opened_on links from DEV-F90D2",
      len([l for l in links if l[1] == device_ring and l[4] == "opened_on"]) == 4)
check("B: 4 inbound transfers, all under the 2,500 reporting line",
      len(ring_inbound) == 4 and all(2000 <= x < 2500 for x in ring_inbound))
check("B: every member forwarded its inbound within 3 minutes",
      len([t for t in txns if t[8] in ("ACC-7771", "ACC-7702", "ACC-7745") and t[5] == "outbound"]) == 3)
# L-203's pass_through_ratio uses fanout_policy='min' across the ring's accounts,
# so the rule can only fire once EVERY member has forwarded. This mirrors that
# reduction at both point-in-time bounds — it is the fixture-side proof that
# evaluation_lag is load-bearing rather than decorative.
def _min_ratio_at(bound):
    ratios = []
    for aid, _role in ring_accts:
        ins = sum(t[2] for t in txns if t[8] == aid and t[5] == "inbound" and t[1] <= bound)
        outs = sum(t[2] for t in txns if t[8] == aid and t[5] == "outbound" and t[1] <= bound)
        ratios.append(outs / ins if ins else 0.0)
    return min(ratios)


_r_at_trigger = _min_ratio_at(ring_last_inbound)
_r_at_lag = _min_ratio_at(ring_last_inbound + timedelta(minutes=15))
check("B: min pass-through ratio is under L-203's 0.9 line at the trigger",
      _r_at_trigger <= 0.9, f"{_r_at_trigger:.2f} — so lag=0 must not fire")
check("B: min pass-through ratio clears 0.9 fifteen minutes later",
      _r_at_lag > 0.9, f"{_r_at_lag:.2f} — so lag=15m must fire")

check("C: password_reset 11 min before the transfer",
      (transfer_time - reset_time).total_seconds() / 60 == 11.0)
check("C: payee_added 4 min before the transfer",
      (transfer_time - payee_time).total_seconds() / 60 == 4.0)
_bal = round(sum(t[2] for t in txns if t[8] == acct2201 and t[1] < transfer_time
                 and t[5] in ("credit", "inbound"))
             - sum(t[2] for t in txns if t[8] == acct2201 and t[1] < transfer_time
                   and t[5] in ("debit", "outbound") and t[14] == "approved"), 2)
check("C: ACC-2201 balance before the transfer equals the transfer amount",
      abs(_bal - AVAIL_BALANCE) < 0.01, f"{_bal:.2f} vs {AVAIL_BALANCE:.2f}")
check("C: the transfer leaves from a datacenter IP", dc_ip in DATACENTER_IPS)

check("D: an MCC-4511 purchase for CUST-MENSAH within 7d of the flagged charge",
      bool([t for t in txns_where(customer_id=mensah, mcc=MCC_AIRLINE)
            if rest_time - timedelta(days=7) <= t[1] <= rest_time]))
check("D: the ticket is booked from GB, so PT stays new for the customer",
      not [t for t in txns_where(customer_id=mensah, txn_country="PT")
           if t[1] <= rest_time - timedelta(days=1)])

check("E: 5 CNP charges on CARD-VETO within 90s of TXN-48300",
      len([t for t in txns_where(card_id=veto_card, channel="cnp")
           if veto_time - timedelta(seconds=90) < t[1] <= veto_time]) == 5)
check("E: TXN-48300 is card-present chip-and-PIN", txns_where(txn_id=FLAG_E)[0][13] == "chip_pin")
check("E: PT is NOT new for CUST-VETO, so T-021's +50 stays silent",
      bool([t for t in txns_where(customer_id=veto_cust, txn_country="PT")
            if t[1] <= veto_time - timedelta(days=1)]))
check("E: MCC 5813 is new for CUST-VETO",
      not [t for t in txns_where(customer_id=veto_cust, mcc=MCC_BAR)
           if t[1] <= veto_time - timedelta(days=1)])

_mt = txns_where(merchant_id="MER-TEST", auth_result="declined")
check("s14: MER-TEST has 22 declines inside a 10-minute window",
      len(_mt) == 22 and (max(t[1] for t in _mt) - min(t[1] for t in _mt)) <= timedelta(minutes=10),
      f"{len(_mt)} over {(max(t[1] for t in _mt) - min(t[1] for t in _mt))}")
_worst, _worst_mer, _dec_by_mer = 0, None, {}
for t in txns:
    if t[14] == "declined" and t[10] and t[10] != "MER-TEST":
        _dec_by_mer.setdefault(t[10], []).append(t[1])
for mer, ts in _dec_by_mer.items():
    ts.sort()
    for i, t0 in enumerate(ts):
        n = sum(1 for t1 in ts[i:] if t1 - t0 <= timedelta(minutes=10))
        if n > _worst:
            _worst, _worst_mer = n, mer
check("s14: no other merchant exceeds 2 declines in any 10-minute window",
      _worst <= 2, f"worst is {_worst} at {_worst_mer}")

_n_declined = len(txns_where(auth_result="declined"))
_n_refund = len(txns_where(txn_type="refund"))
_n_fraud = len(txns_where(synthetic_label="fraud"))
check("population: decline rate between 2% and 5%",
      0.02 <= _n_declined / len(txns) <= 0.05, f"{_n_declined} ({_n_declined/len(txns):.1%})")
check("population: refund rate between 1% and 3%",
      0.01 <= _n_refund / len(txns) <= 0.03, f"{_n_refund} ({_n_refund/len(txns):.1%})")
check("population: fraud-labelled between 1% and 4%",
      0.01 <= _n_fraud / len(txns) <= 0.04, f"{_n_fraud} ({_n_fraud/len(txns):.1%})")
check("population: every transaction carries a label",
      not [t for t in txns if t[_IDX["synthetic_label"]] not in ("fraud", "legit")])
check("refund abuse: CUST-REFUND refunds ~87% of purchase value",
      0.85 <= _ref_emitted / _ref_total <= 0.89, f"{_ref_emitted/_ref_total:.1%}")
check("cohort: 6 of 22 fraud clusters are shaped to be catchable",
      cohort_expect_detected == 6, f"{cohort_expect_detected}/22")

print("\nALL STRUCTURAL CHECKS PASS." if not failures
      else f"\n*** {len(failures)} STRUCTURAL CHECK(S) FAILED ***")
sys.exit(0 if not failures else 1)
